#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          doctor-schedule-client:
#            provider: tacocloud
#            client-id: doctor-schedule-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: http://127.0.0.1:9001/authorized/{registrationId}
#            scope: write,delete
#        provider:
#          tacocloud:
#            issuer-uri: http://127.0.0.1:9000
